// <auto-generated />
using System;
using DietSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietSync.Infrastructure.Migrations
{
    [DbContext(typeof(DietSyncDbContext))]
    partial class DietSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DietSync.Core.Entities.Dieta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_dieta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alimentos")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("alimentos");

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("calorias");

                    b.Property<decimal>("Carboidratos")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("carboidratos");

                    b.Property<string>("DataDieta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("data_dieta");

                    b.Property<decimal>("Gorduras")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("gorduras");

                    b.Property<string>("NomeDieta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_dieta");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("proteinas");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refeicao");

                    b.Property<string>("TipoDieta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo_dieta");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("dietas", (string)null);
                });

            modelBuilder.Entity("DietSync.Core.Entities.Evolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("altura");

                    b.Property<decimal>("Cintura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cintura");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("peso");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("evolucaos", (string)null);
                });

            modelBuilder.Entity("DietSync.Core.Entities.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("calorias");

                    b.Property<decimal>("Carboidratos")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("carboidratos");

                    b.Property<decimal>("Gorduras")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("gorduras");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredientes");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("modo_preparo");

                    b.Property<string>("NomeReceita")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_receita");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("proteinas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("receita", (string)null);
                });

            modelBuilder.Entity("DietSync.Core.Entities.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("DiaTreino")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("Duracao")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("duracao");

                    b.Property<string>("Exercicios")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercicios");

                    b.Property<int>("Frequencia")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("frequencia");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_treino");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("objetivo");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int")
                        .HasColumnName("repeticoes");

                    b.Property<int>("Series")
                        .HasColumnType("int")
                        .HasColumnName("series");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("treino", (string)null);
                });

            modelBuilder.Entity("DietSync.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("altura");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("date")
                        .HasColumnName("data_nasc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("DietSync.Core.Entities.Dieta", b =>
                {
                    b.HasOne("DietSync.Core.Entities.User", "User")
                        .WithMany("Dietas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietSync.Core.Entities.Evolucao", b =>
                {
                    b.HasOne("DietSync.Core.Entities.User", "User")
                        .WithMany("Evolucoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietSync.Core.Entities.Receita", b =>
                {
                    b.HasOne("DietSync.Core.Entities.User", "User")
                        .WithMany("Receitas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietSync.Core.Entities.Treino", b =>
                {
                    b.HasOne("DietSync.Core.Entities.User", "User")
                        .WithMany("Treinos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietSync.Core.Entities.User", b =>
                {
                    b.Navigation("Dietas");

                    b.Navigation("Evolucoes");

                    b.Navigation("Receitas");

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
